BankAccountSimulation/BankAccountSimulation/Controllers/AccountStatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogicLayer.Contracts;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace BankAccountSimulation.Controllers
{
    public class AccountStatusController : Controller
    {
        private readonly IAccountStatusManager _iAccountStatusManager;

        public AccountStatusController(IAccountStatusManager iAccountStatusManager)
        {
            _iAccountStatusManager = iAccountStatusManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("AdminId") != null)
                return View(_iAccountStatusManager.GetAll());
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("AdminId") != null)
                return View();
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Create(AccountStatus aAccountStatus)
        {
            if (ModelState.IsValid)
            {
                bool isAdd = _iAccountStatusManager.Add(aAccountStatus);

                if (isAdd)
                    return RedirectToAction("Index");
                else
                    return ViewBag.ErrorMessage = "Account type has been save to failed!";
            }

            return View(aAccountStatus);
        }

        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                if (id == null)
                    return NotFound();

                AccountStatus aAccountStatus = _iAccountStatusManager.GetById(id);

                if (aAccountStatus == null)
                    return NotFound();

                return View(aAccountStatus);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Update(AccountStatus aAccountStatus)
        {
            if (ModelState.IsValid)
            {
                bool isUpdate = _iAccountStatusManager.Update(aAccountStatus);

                if (isUpdate)
                    return RedirectToAction("Index");
                else
                    return ViewBag.ErrorMessage = "Account type update failed!";
            }

            return View(aAccountStatus);
        }

        [HttpGet]
        public IActionResult Remove(int? id)
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                if (id == null)
                    return NotFound();

                AccountStatus aAccountStatus = _iAccountStatusManager.GetById(id);

                if (aAccountStatus == null)
                    return NotFound();

                return View(aAccountStatus);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Remove(AccountStatus aAccountStatus)
        {
            bool isRemove = _iAccountStatusManager.Remove(aAccountStatus);

            if (isRemove)
                return RedirectToAction("Index");
            else
                return ViewBag.ErrorMessage = "Account type remove failed!";
        }
    }
}

BankAccountSimulation/BankAccountSimulation/Views/AccountStatus/Create.cshtml
@using Models
@model AccountStatus

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1 class="haderTitle">Create Account Status</h1>
<hr />

<div class="row" id="createFrom">
    <div class="col-md-12">
        <form method="post" asp-action="Create">
            <div class="form-group">
                <label asp-for="Name" class="col-md-2 control-lable">Name</label>
                <div class="col-md-5">
                    <input type="text" asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <span class="text-danger">@ViewBag.ErrorMessage</span>
                    <input type="submit" value="Create" class="btn btn-success" />
                    <a asp-action="Index" class="btn btn-info"><i class="far fa-list-alt"></i> Back To List</a>
                </div>
            </div>
        </form>
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

BankAccountSimulation/BankAccountSimulation/Views/AccountStatus/Index.cshtml
@using Models
@model IEnumerable<AccountStatus>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1 class="haderTitle">Account Status Details</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <a asp-action="Create" asp-controller="AccountStatus" class="btn btn-primary"><i class="fas fa-user-plus"></i> Create Account Status</a>
    </div>
</div>

<div class="row" id="styleDataTableCountry">
    <div class="col-md-5">
        <table id="dataTable" class="display table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (AccountStatus item in Model)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>
                            <a asp-route-id="@item.Id" asp-action="Update" class="btn btn-info"><i class="fas fa-external-link-alt"></i> Edit</a>
                            <a asp-route-id="@item.Id" asp-action="Remove" class="btn btn-danger"><i class="fas fa-trash"></i> Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

BankAccountSimulation/BankAccountSimulation/Views/AccountStatus/Remove.cshtml
@model Models.AccountStatus

@{
    ViewData["Title"] = "Remove";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Remove</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AccountStatus</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Remove">
        <input type="hidden" asp-for="Id" />
        <span class="text-danger">@ViewBag.ErrorMessage</span>
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BankAccountSimulation/BankAccountSimulation/Views/AccountStatus/Update.cshtml
@using Models
@model AccountStatus

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1 class="haderTitle">Update Account Status</h1>
<hr />

<div class="row" id="updateFrom">
    <div class="col-md-12">
        <form method="post" asp-action="Update">
            <div class="form-group">
                <label asp-for="Name" class="col-md-2 control-lable">Name</label>
                <div class="col-md-5">
                    <input type="text" asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <span class="text-danger">@ViewBag.ErrorMessage</span>
                    <input type="submit" value="Create" class="btn btn-success" />
                    <a asp-action="Index" class="btn btn-info"><i class="far fa-list-alt"></i> Back To List</a>
                </div>
            </div>
        </form>
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>