BankAccountSimulation/BankAccountSimulation/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogicLayer.Contracts;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace BankAccountSimulation.Controllers
{
    public class AdminController : Controller
    {
        private readonly IAdminManager _iAdminManager;

        public AdminController(IAdminManager iAdminManager)
        {
            _iAdminManager = iAdminManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                ICollection<Admin> adminList = _iAdminManager.GetAll();
                return View(adminList);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                return View();
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Create(Admin aAdmin)
        {
            if(ModelState.IsValid)
            {
                bool isAdd = _iAdminManager.Add(aAdmin);

                if (isAdd)
                    return RedirectToAction("Index");
                else
                    return ViewBag.ErrorMessage = "Admin create failed!";
            }

            return View(aAdmin);
        }

        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                if (id == null)
                    return NotFound();

                Admin aAdminDetails = _iAdminManager.GetById(id);

                if (aAdminDetails == null)
                    return NotFound();

                return View(aAdminDetails);
            }
            else
                return RedirectToAction("Index", "Home");                 
        }

        [HttpPost]
        public IActionResult Update(Admin aAdmin)
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                if (ModelState.IsValid)
                {
                    bool isUpdate = _iAdminManager.Update(aAdmin);

                    if (isUpdate)
                        return RedirectToAction("Index");
                    else
                        return ViewBag.ErrorMessage = "Admin update failed!";
                }

                return View(aAdmin);
            }
            else
                return RedirectToAction("Index", "Home");              
        }

        [HttpGet]
        public IActionResult Remove(int? id)
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                if (id == null)
                    return NotFound();

                Admin aAdminDetails = _iAdminManager.GetById(id);

                if (aAdminDetails == null)
                    return NotFound();

                return View(aAdminDetails);
            }
            else
                return RedirectToAction("Index", "Home");                  
        }

        [HttpPost]
        public IActionResult Remove(Admin aAdmin)
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                bool isRemove = _iAdminManager.Remove(aAdmin);

                if (isRemove)
                    return RedirectToAction("Index");
                else
                    return ViewBag.ErrorMessage = "Admin delete failed!";
            }
            else
                return RedirectToAction("Index", "Home");                           
        }
    }
}

BankAccountSimulation/BankAccountSimulation/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogicLayer.Contracts;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models;

namespace BankAccountSimulation.Controllers
{
    public class BranchController : Controller
    {
        private readonly IBranchManager _iBranchManager;
        private readonly ICountryManager _iCountryManager;
        private readonly ICityManager _iCityManager;

        public BranchController(IBranchManager iBranchManager, 
                                ICountryManager iCountryManager, ICityManager iCityManager)
        {
            _iBranchManager = iBranchManager;
            _iCountryManager = iCountryManager;
            _iCityManager = iCityManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("AdminId") != null)
                return View(_iBranchManager.GetBranchWithCountryAndCity());
            else
                return RedirectToAction("Index", "Home");
        }

        private List<SelectListItem> CountryList()
        {
            List<SelectListItem> countryList = _iCountryManager.GetAll()
                                                .Select(c=> new SelectListItem 
                                                { 
                                                    Value = c.Id.ToString(),
                                                    Text = c.Name,
                                                }).ToList();
            return countryList;
        }

        private List<SelectListItem> CityList()
        {
            List<SelectListItem> cityList = _iCityManager.GetAll()
                                                .Select(c => new SelectListItem
                                                {
                                                    Value = c.Id.ToString(),
                                                    Text = c.Name,
                                                }).ToList();
            return cityList;
        }

        [Route("api/[controller]/[action]")]
        public JsonResult GetCityByCountryId(int countryId)
        {
            ICollection<City> cityList = _iBranchManager.GetCityByCountryId(countryId);
            return Json(cityList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                ViewBag.CountryList = CountryList();
                return View();
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Create(Branch aBranch)
        {
            if(ModelState.IsValid)
            {
                bool isAdd = _iBranchManager.Add(aBranch);

                if (isAdd)
                    return RedirectToAction("Index");
                else
                    return ViewBag.ErrorMessage = "Branch has been not save!";
            }

            ViewBag.CountryList = CountryList();
            return View(aBranch);
        }

        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                if (id == null)
                    return NotFound();

                Branch aBranchDetails = _iBranchManager.GetById(id);

                if (aBranchDetails == null)
                    return NotFound();

                ViewBag.CountryList = CountryList();
                ViewBag.CityList = CityList();
                return View(aBranchDetails);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Update(Branch aBranch)
        {
            if(ModelState.IsValid)
            {
                bool isUpdate = _iBranchManager.Update(aBranch);

                if (isUpdate)
                    return RedirectToAction("Index");
                else
                    return ViewBag.ErrorMessage = "Branch failed to update!";
            }

            ViewBag.CountryList = CountryList();
            ViewBag.CityList = CityList();
            return View(aBranch);
        }

        [HttpGet]
        public IActionResult Remove(int? id)
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                if (id == null)
                    return NotFound();

                Branch aBranchDetails = _iBranchManager.GetById(id);

                if (aBranchDetails == null)
                    return NotFound();

                ViewBag.CountryList = CountryList();
                ViewBag.CityList = CityList();
                return View(aBranchDetails);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Remove(Branch aBranch)
        {
            bool isRemove = _iBranchManager.Remove(aBranch);

            if (isRemove)
                return RedirectToAction("Index");
            else
                return ViewBag.ErrorMessage = "Branch remove failed!";
        }
    }
}

BankAccountSimulation/BankAccountSimulation/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogicLayer.Contracts;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models;

namespace BankAccountSimulation.Controllers
{
    public class CityController : Controller
    {
        private readonly ICityManager _iCityManager;
        private readonly ICountryManager _iCountryManager;

        public CityController(ICityManager iCityManager, ICountryManager iCountryManager)
        {
            _iCityManager = iCityManager;
            _iCountryManager = iCountryManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("AdminId") != null)
                return View(_iCityManager.GetCityWithCountry());
            else
                return RedirectToAction("Index", "Home");
        }

        private List<SelectListItem> GetAllCountry()
        {
            List<SelectListItem> countryList = _iCountryManager.GetAll()
                                               .Select(c=> new SelectListItem 
                                               { 
                                                    Value = c.Id.ToString(),
                                                    Text = c.Name 
                                               }).ToList();
            return countryList;
        }

        [HttpGet]
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                ViewBag.CountryList = GetAllCountry();
                return View();
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Create(City aCity)
        {
            if(ModelState.IsValid)
            {
                bool isAdd = _iCityManager.Add(aCity);

                if (isAdd)
                    return RedirectToAction("Index");
                else
                    return ViewBag.ErrorMessage = "City save failed!";
            }

            ViewBag.CountryList = GetAllCountry();
            return View(aCity);
        }

        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                if (id == null)
                    return NotFound();

                City aCityDetails = _iCityManager.GetById(id);

                if (aCityDetails == null)
                    return NotFound();

                ViewBag.CountryList = GetAllCountry();
                return View(aCityDetails);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Update(City aCity)
        {
            if(ModelState.IsValid)
            {
                bool isUpdate = _iCityManager.Update(aCity);

                if (isUpdate)
                    return RedirectToAction("Index");
                else
                    return ViewBag.ErrorMessage = "City has been update failed!";
            }

            ViewBag.CountryList = GetAllCountry();
            return View(aCity);
        }

        [HttpGet]
        public IActionResult Remove(int? id)
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                if (id == null)
                    return NotFound();

                City aCityDetails = _iCityManager.GetById(id);

                if (aCityDetails == null)
                    return NotFound();

                ViewBag.CountryList = GetAllCountry();
                return View(aCityDetails);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Remove(City aCity)
        {
            bool isRemove = _iCityManager.Remove(aCity);

            if (isRemove)
                return RedirectToAction("Index");
            else
                return ViewBag.ErrorMessage = "City remove failed!";
        }
    }
}

BankAccountSimulation/BankAccountSimulation/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogicLayer.Contracts;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace BankAccountSimulation.Controllers
{
    public class CountryController : Controller
    {
        private readonly ICountryManager _iCountryManager;

        public CountryController(ICountryManager iCountryManager)
        {
            _iCountryManager = iCountryManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("AdminId") != null)
                return View(_iCountryManager.GetAll());
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("AdminId") != null)
                return View();
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Create(Country aCountry)
        {
            if(ModelState.IsValid)
            {
                bool isAdd = _iCountryManager.Add(aCountry);

                if (isAdd)
                    return RedirectToAction("Index");
                else
                    return ViewBag.ErrorMessage = "Country save failed!";
            }

            return View(aCountry);
        }

        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                if (id == null)
                    return NotFound();

                Country aCountryDetails = _iCountryManager.GetById(id);

                if (aCountryDetails == null)
                    return NotFound();

                return View(aCountryDetails);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Update(Country aCountry)
        {
            if(ModelState.IsValid)
            {
                bool isUpdate = _iCountryManager.Update(aCountry);

                if (isUpdate)
                    return RedirectToAction("Index");
                else
                    return ViewBag.ErrorMessage = "Country update failed!";
            }

            return View(aCountry);
        }

        [HttpGet]
        public IActionResult Remove(int? id)
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                if (id == null)
                    return NotFound();

                Country aCountryDetails = _iCountryManager.GetById(id);

                if (aCountryDetails == null)
                    return NotFound();

                return View(aCountryDetails);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Remove(Country aCountry)
        {
            bool isRemove = _iCountryManager.Remove(aCountry);

            if (isRemove)
                return RedirectToAction("Index");
            else
                return ViewBag.ErrorMessage = "Counter remove failed!";
        }
    }
}

BankAccountSimulation/BankAccountSimulation/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Http

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <!-- Title -->
    <title>@ViewData["Title"]</title>

    <link href="~/font-awesome/css/all.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Trade+Winds&display=swap" rel="stylesheet">
    <link href="~/css/customCss.css" rel="stylesheet" />
    <link href="~/datatables/css/jquery.dataTables.css" rel="stylesheet" />

    <!-- Favicon -->
    <link rel="icon" href="~/dashboard-layout/img/core-img/favicon.ico">                                   
    <link href="~/dashboard-layout/style.css" rel="stylesheet" />      
</head>

<body>
    <!-- Preloader -->
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="lds-ellipsis">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <!-- ##### Header Area Start ##### -->
    <header class="header-area">
        <!-- Top Header Area -->
        <!-- Navbar Area -->
        <div class="credit-main-menu" id="sticker">
            <div class="classy-nav-container breakpoint-off">
                <div class="container">
                    <!-- Menu -->
                    <nav class="classy-navbar justify-content-between" id="creditNav"> 
                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>  
                        <!-- Menu -->
                        <div class="classy-menu">
                            <!-- Close Button -->
                            <div class="classycloseIcon">
                                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                            </div>    
                            <!-- Nav Start -->
                            <div class="classynav">
                                <ul>
                                    <li><a asp-action="Index" asp-controller="Admin">Admin</a></li>
                                    <li>
                                        <a href="#">References</a>
                                        <ul class="dropdown">
                                            <li><a asp-action="Index" asp-controller="Country">Country</a></li>
                                            <li><a asp-action="Index" asp-controller="City">City</a></li>
                                        </ul>
                                    </li>
                                    <li><a asp-action="Index" asp-controller="Branch">Branch</a></li>
                                    <li>
                                        <a href="#">Customer Info</a>
                                        <ul class="dropdown">
                                            <li><a asp-action="Index" asp-controller="Customer">Cusstomer</a></li>
                                            <li><a asp-action="TransferMoneyRecordAdmin" asp-controller="TransferMoney">Transfer Money</a></li>
                                            <li><a asp-action="Index" asp-controller="WithdrawMoney">Withdraw Money</a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="#">Account References</a>
                                        <ul class="dropdown">
                                            <li><a asp-action="Index" asp-controller="AccountType">Account Type</a></li>
                                            <li><a asp-action="Index" asp-controller="AccountStatus">Account Status</a></li>
                                            <li><a asp-action="Index" asp-controller="Account">Account</a></li>
                                        </ul>
                                    </li>
                                    @if (Context.Session.GetString("AdminId") != null)
                                    {
                                        <li><a asp-action="AdminLogout" asp-controller="LoginLogout">Logout</a></li>

                                    }
                                </ul>
                            </div>
                            <!-- Nav End -->
                        </div>      
                        <!-- Contact -->
                        <div class="contact">
                            <a href="#">
                                <img src="~/dashboard-layout/img/core-img/call2.png" /> +800 49 900 900
                            </a>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ##### Header Area End ##### --> 
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>   
    <!-- ##### All Javascript Script ##### -->
    <!-- jQuery-2.2.4 js -->                                                
    <script src="~/dashboard-layout/js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="~/font-awesome/js/all.js"></script>
    <script src="~/datatables/js/jquery.dataTables.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/dashboard-layout/js/bootstrap/popper.min.js"></script>
    <script src="~/dashboard-layout/js/plugins/plugins.js"></script>
    <script src="~/dashboard-layout/js/active.js"></script>

    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable();
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>       
</html>

BankAccountSimulation/BankAccountSimulation/Views/Shared/_CustomerLayout.cshtml
@using Microsoft.AspNetCore.Http

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <!-- Title -->
    <title>@ViewData["Title"]</title>

    <link href="~/font-awesome/css/all.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Trade+Winds&display=swap" rel="stylesheet">
    <link href="~/css/customCss.css" rel="stylesheet" />
    <link href="~/datatables/css/jquery.dataTables.css" rel="stylesheet" />

    <!-- Favicon -->
    <link rel="icon" href="~/dashboard-layout/img/core-img/favicon.ico">
    <link href="~/dashboard-layout/style.css" rel="stylesheet" />
</head>

<body>
    <!-- Preloader -->
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="lds-ellipsis">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <!-- ##### Header Area Start ##### -->
    <header class="header-area">
        <!-- Top Header Area -->
        <!-- Navbar Area -->
        <div class="credit-main-menu" id="sticker">
            <div class="classy-nav-container breakpoint-off">
                <div class="container">
                    <!-- Menu -->
                    <nav class="classy-navbar justify-content-between" id="creditNav">
                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>
                        <!-- Menu -->
                        <div class="classy-menu">
                            <!-- Close Button -->
                            <div class="classycloseIcon">
                                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                            </div>
                            <!-- Nav Start -->
                            <div class="classynav">
                                <ul>
                                    <li><a asp-action="LoginCustomerInfo" asp-controller="LoginCustomer">My Information</a></li>
                                    <li><a asp-action="LoginCustomerAccountInfo" asp-controller="LoginCustomer">Account Information</a></li>
                                    <li><a asp-action="TransferMoneyRecord" asp-controller="TransferMoney">Transfer Money</a></li>
                                    <li><a asp-action="LoginCustomerIndex" asp-controller="WithdrawMoney">Withdraw Money</a></li>
                                    @if (Context.Session.GetString("CustomerId") != null)
                                    {
                                        <li><a asp-action="CustomerLogout" asp-controller="LoginLogout">Logout</a></li>
                                    }

                                    @*<li>
            <a href="#">References</a>
            <ul class="dropdown">
                <li><a asp-action="Index" asp-controller="Country">Country</a></li>
                <li><a asp-action="Index" asp-controller="City">City</a></li>
            </ul>
        </li>
        <li><a asp-action="Index" asp-controller="Branch">Branch</a></li>
        <li><a asp-action="Index" asp-controller="Customer">Cusstomer</a></li>
        <li>
            <a href="#">Account References</a>
            <ul class="dropdown">
                <li><a asp-action="Index" asp-controller="AccountType">Account Type</a></li>
                <li><a asp-action="Index" asp-controller="AccountStatus">Account Status</a></li>
                <li><a asp-action="Index" asp-controller="Account">Account</a></li>
            </ul>
        </li>*@
                                </ul>
                            </div>
                            <!-- Nav End -->
                        </div>
                        <!-- Contact -->
                        <div class="contact">
                            <a href="#">
                                <img src="~/dashboard-layout/img/core-img/call2.png" /> +800 49 900 900
                            </a>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ##### Header Area End ##### -->
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- ##### All Javascript Script ##### -->
    <!-- jQuery-2.2.4 js -->
    <script src="~/dashboard-layout/js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="~/font-awesome/js/all.js"></script>
    <script src="~/datatables/js/jquery.dataTables.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/dashboard-layout/js/bootstrap/popper.min.js"></script>
    <script src="~/dashboard-layout/js/plugins/plugins.js"></script>
    <script src="~/dashboard-layout/js/active.js"></script>

    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable();
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BankAccountSimulation/BankAccountSimulation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>  
    <link href="~/font-awesome/css/all.css" rel="stylesheet" />
    <link href="~/jqueryui/jquery-ui.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Trade+Winds&display=swap" rel="stylesheet">
    <link href="~/css/customCss.css" rel="stylesheet" />
    <link href="~/datatables/css/jquery.dataTables.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BankAccountSimulation</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>        
                    </ul>                       
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BankAccountSimulation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/font-awesome/js/all.js"></script>
    <script src="~/jqueryui/jquery-ui.js"></script>
    <script src="~/datatables/js/jquery.dataTables.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        $(document).ready( function () {
            $('#dataTable').DataTable();
        } );
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>