BankAccountSimulation/BankAccountSimulation/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogicLayer.Contracts;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models;

namespace BankAccountSimulation.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerManager _iCustomerMamager;
        private readonly IBranchManager _iBranchManager;
        [Obsolete]
        private readonly IHostingEnvironment _iHostingEnvironment;

        [Obsolete]
        public CustomerController(ICustomerManager iCustomerManager, 
                                  IBranchManager iBranchManager, 
                                  IHostingEnvironment iHostingEnvironment)
        {
            _iCustomerMamager = iCustomerManager;
            _iBranchManager = iBranchManager;
            _iHostingEnvironment = iHostingEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("AdminId") != null)
                return View(_iCustomerMamager.GetCustomerWithBranch());
            else
                return RedirectToAction("Index", "Home");
        }

        private List<SelectListItem> BranchList()
        {
            List<SelectListItem> branchList = _iBranchManager.GetAll()
                                            .Select(c => new SelectListItem 
                                            { 
                                                Value = c.Id.ToString(),
                                                Text = c.Name
                                            }).ToList();
            return branchList;
        }

        [HttpGet]
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                ViewBag.BranchList = BranchList();
                return View();
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [Obsolete]
        public IActionResult Create(Customer aCustomer, IFormFile picture)
        {
            if(ModelState.IsValid)
            {
                if(picture != null)
                {
                    string nameAndPath = Path.Combine(_iHostingEnvironment.WebRootPath
                                                  + "/CustomerPictures",
                                                  Path.GetFileName(picture.FileName)); 
                    picture.CopyToAsync(new FileStream(nameAndPath, FileMode.Create));
                    aCustomer.Picture = "CustomerPictures/" + picture.FileName;
                }

                if (picture == null)
                    aCustomer.Picture = "CustomerPictures/NoImageFound.png";

                bool isAdd = _iCustomerMamager.Add(aCustomer);

                if (isAdd)
                    return RedirectToAction("Index");
                else
                    return ViewBag.ErrorMessage = "Customer save has been failed!";
            }

            return View(aCustomer);
        }

        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                if (id == null)
                    return NotFound();

                Customer aCustomer = _iCustomerMamager.GetById(id);

                if (aCustomer == null)
                    return NotFound();

                ViewBag.BranchList = BranchList();
                return View(aCustomer);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [Obsolete]
        public IActionResult Update(Customer aCustomer, IFormFile picture, string pic)
        {
            if(ModelState.IsValid)
            {
                if (picture != null)
                {
                    string nameAndPath = Path.Combine(_iHostingEnvironment.WebRootPath
                                                  + "/CustomerPictures",
                                                  Path.GetFileName(picture.FileName));
                    picture.CopyToAsync(new FileStream(nameAndPath, FileMode.Create));
                    aCustomer.Picture = "CustomerPictures/" + picture.FileName;
                }

                if (picture == null)
                    aCustomer.Picture = pic;

                bool isUpdate = _iCustomerMamager.Update(aCustomer);

                if (isUpdate)
                    return RedirectToAction("Index");
                else
                    return ViewBag.ErrorMessage = "Customer failed to update!";
            }

            ViewBag.BranchList = BranchList();
            return View(aCustomer);
        }

        [HttpGet]
        public IActionResult Remove(int? id)
        {
            if (HttpContext.Session.GetString("AdminId") != null)
            {
                if (id == null)
                    return NotFound();

                Customer aCustomer = _iCustomerMamager.ACustomerWithBranch(id);

                if (aCustomer == null)
                    return NotFound();

                return View(aCustomer);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Remove(Customer aCustomer)
        {
            bool isRemove = _iCustomerMamager.Remove(aCustomer);

            if (isRemove)
                return RedirectToAction("Index");
            else
                return ViewBag.ErrorMessage = "Customer remove failed!";
        }

        [Route("api/[controller]/[action]")]
        public JsonResult CheckExistEmail(string customerEmail)
        {
            string existEmail = _iCustomerMamager.ExistEmail(customerEmail);

            if (existEmail != null)
                return Json(1);
            else
                return Json(0);
        }                                       
    }
}

BankAccountSimulation/BankAccountSimulation/Controllers/LoginCustomerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogicLayer.Contracts;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models;

namespace BankAccountSimulation.Controllers
{
    public class LoginCustomerController : Controller
    {
        private readonly ICustomerManager _iCustomerManager;
        private readonly IBranchManager _iBranchManager;
        private readonly IAccountManager _iAccountManager;
        [Obsolete]
        private readonly IHostingEnvironment _iHostingEnvironment;

        [Obsolete]
        public LoginCustomerController(ICustomerManager iCustomerManager,
                                      IHostingEnvironment iHostingEnvironment, IBranchManager iBranchManager,
                                      IAccountManager iAccountManager)
        {
            _iCustomerManager = iCustomerManager;
            _iHostingEnvironment = iHostingEnvironment;
            _iBranchManager = iBranchManager;
            _iAccountManager = iAccountManager;
        }

        private List<SelectListItem> BranchList()
        {
            List<SelectListItem> branchList = _iBranchManager.GetAll()
                                            .Select(c => new SelectListItem
                                            {
                                                Value = c.Id.ToString(),
                                                Text = c.Name
                                            }).ToList();
            return branchList;
        }

        private Customer LoginCustomer()
        {
            string customerId = HttpContext.Session.GetString("CustomerId");
            int convertCustomerId = Convert.ToInt32(customerId);
            Customer loginCustomerInfo = _iCustomerManager.ACustomerWithBranch(convertCustomerId);
            return loginCustomerInfo;
        }

        [HttpGet]
        public IActionResult LoginCustomerInfo()
        {
            if (HttpContext.Session.GetString("CustomerId") != null)
            {
                Customer loginCustomerInfo = LoginCustomer();
                return View(loginCustomerInfo);
            }
            else
                return RedirectToAction("CustomerLogin", "LoginLogout");
        }

        [HttpGet]
        public IActionResult LoginCustomerUpdate(int? id)
        {
            if (HttpContext.Session.GetString("CustomerId") != null)
            {
                if (id == null)
                    return NotFound();

                Customer aCustomer = _iCustomerManager.GetById(id);

                if (aCustomer == null)
                    return NotFound();

                ViewBag.BranchList = BranchList();
                return View(aCustomer);
            }
            else
                return RedirectToAction("CustomerLogin", "LoginLogout");
        }

        [HttpPost]
        [Obsolete]
        public IActionResult LoginCustomerUpdate(Customer aCustomer, IFormFile picture, string pic)
        {
            if (ModelState.IsValid)
            {
                if (picture != null)
                {
                    string nameAndPath = Path.Combine(_iHostingEnvironment.WebRootPath
                                                  + "/CustomerPictures",
                                                  Path.GetFileName(picture.FileName));
                    picture.CopyToAsync(new FileStream(nameAndPath, FileMode.Create));
                    aCustomer.Picture = "CustomerPictures/" + picture.FileName;
                }

                if (picture == null)
                    aCustomer.Picture = pic;

                bool isUpdate = _iCustomerManager.Update(aCustomer);

                if (isUpdate)
                    return RedirectToAction("LoginCustomerInfo");
                else
                    return ViewBag.ErrorMessage = "Customer failed to update!";
            }
            else
            {
                ViewBag.BranchList = BranchList();
                return View(aCustomer);
            }
        }

        [HttpGet]
        public IActionResult LoginCustomerAccountInfo()
        {
            if (HttpContext.Session.GetString("CustomerId") != null)
            {
                Customer loginCustomerInfo = LoginCustomer();
                int loginCustomerId = loginCustomerInfo.Id;
                Account loginCustomerAccountInfo = _iAccountManager
                                                   .GetLoginCustomerAccountByIncluding(loginCustomerId);
                return View(loginCustomerAccountInfo);
            }
            else
                return RedirectToAction("CustomerLogin", "LoginLogout");
        }
    }
}

BankAccountSimulation/BankAccountSimulation/Views/LoginCustomer/LoginCustomerAccountInfo.cshtml
@using Models
@model Account

@{
    ViewData["Title"] = "Login Custome Account Information";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}

<h1 class="haderTitle">Account Details</h1>

<div class="row" id="styleDataTableCountry">
    <div class="col-md-10">
        <table class="display table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Basic Info</th>
                    <th>Account Info</th> 
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Branch: @Model.Branch.Name <br />
                        Type: @Model.AccountType.Name <br />
                        Status: @Model.AccountStatus.Name <br />
                    </td>
                    <td>
                        Customer: @Model.Customer.Name <br />
                        AC No: @Model.AccountNumber <br />
                        Balance: @Model.Balance <br />
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

BankAccountSimulation/BankAccountSimulation/Views/LoginCustomer/LoginCustomerInfo.cshtml
@using Models
@model Customer

@{
    ViewData["Title"] = "Customer Information";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}

<h1 class="haderTitle">Customer Information</h1>

<div class="row" id="styleDataTableCustomer">
    <div class="col-md-12">
        <table class="display table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Basic Info</th>
                    <th>Branch And Join Date</th>
                    <th>Picture</th>
                    <th>Action</th>

                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Name: @Model.Name <br />
                        Email: @Model.Email <br />
                        Contact: @Model.ContactNo <br />
                    </td>
                    <td>
                        Join Date: @Model.JoinDate <br />
                        Branch: @Model.Branch.Name <br />
                        Address: <address> @Model.Address </address> <br />
                    </td>
                    <td>
                        <img src="~/@Model.Picture" height="140" width="125" />
                    </td>
                    <td>
                        <a asp-route-id="@Model.Id" asp-action="LoginCustomerUpdate" asp-controller="LoginCustomer" class="btn btn-info"><i class="fas fa-external-link-alt"></i> Edit</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

BankAccountSimulation/BankAccountSimulation/Views/LoginCustomer/LoginCustomerUpdate.cshtml
@using Models
@model Customer

@{
    ViewData["Title"] = "Customer Update";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}

<h1 class="haderTitle">Update My Information</h1>
<hr />

<form method="post" asp-action="LoginCustomerUpdate" asp-controller="Customer" enctype="multipart/form-data" asp-route-pic="@Model.Picture">
    <div class="row">
        <div class="col-md-6" id="customerFromLeft">
            <div class="form-group">
                <label asp-for="Name" class="col-md-2 control-lable">Name</label>
                <div class="col-md-8">
                    <input type="text" asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="col-md-2 control-lable">Password</label>
                <div class="col-md-8">
                    <input type="password" asp-for="Password" value="@Model.Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="ContactNo" class="col-md-5 control-lable">Contact No</label>
                <div class="col-md-8">
                    <input type="number" asp-for="ContactNo" class="form-control" />
                    <span asp-validation-for="ContactNo" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label hidden="hidden" asp-for="BranchId" class="col-md-2 control-lable">Branch</label>
                <div class="col-md-8">
                    <select hidden="hidden" asp-for="BranchId" asp-items="@ViewBag.BranchList" class="form-control">
                    </select>
                    <span asp-validation-for="BranchId" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="col-md-6" id="customerFromRight">
            <div class="form-group">
                <label asp-for="Email" class="col-md-2 control-lable">Email</label>
                <div class="col-md-8">
                    <input type="email" asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="col-md-5 control-lable">Confirm Password</label>
                <div class="col-md-8">
                    <input type="password" asp-for="ConfirmPassword" value="@Model.Password" class="form-control" />
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="JoinDate" class="col-md-5 control-lable">Join Date</label>
                <div class="col-md-8">
                    <input type="text" asp-for="JoinDate" class="form-control" readonly="readonly" />
                    <span asp-validation-for="JoinDate" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="col-md-2 control-lable">Pictuer</label>
                <div class="col-md-8">
                    <input type="file" asp-for="Picture" class="form-control" />
                    <span asp-validation-for="Picture" class="text-danger"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8" id="addressForCustomer">
            <div class="form-group">
                <label asp-for="Address" class="col-md-2 control-lable">Address</label>
                <div class="col-md-8">
                    <textarea asp-for="Address" class="form-control" placeholder="Type your address"></textarea>
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row" id="btnForCustomer">
        <div class="col-md-12">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <span class="text-danger">@ViewBag.ErrorMessage</span>
                    <input type="submit" value="Update" class="btn btn-success" />
                    <a asp-action="LoginCustomerInfo" class="btn btn-info"><i class="far fa-list-alt"></i> Back To Profile</a>
                </div>
            </div>
        </div>
    </div>
</form>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
<script src="~/js/CasecadingDateTimeForCustomer.js"></script>